package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1



/**
 * AgentContactNo generated by hbm2java
 */
public class AgentContactNo  implements java.io.Serializable {


     private Integer agentContactNoId;
     private InsuranceAgent insuranceAgent;
     private String agentContactNo;

    public AgentContactNo() {
    }

	
    public AgentContactNo(InsuranceAgent insuranceAgent) {
        this.insuranceAgent = insuranceAgent;
    }
    public AgentContactNo(InsuranceAgent insuranceAgent, String agentContactNo) {
       this.insuranceAgent = insuranceAgent;
       this.agentContactNo = agentContactNo;
    }
   
    public Integer getAgentContactNoId() {
        return this.agentContactNoId;
    }
    
    public void setAgentContactNoId(Integer agentContactNoId) {
        this.agentContactNoId = agentContactNoId;
    }
    public InsuranceAgent getInsuranceAgent() {
        return this.insuranceAgent;
    }
    
    public void setInsuranceAgent(InsuranceAgent insuranceAgent) {
        this.insuranceAgent = insuranceAgent;
    }
    public String getAgentContactNo() {
        return this.agentContactNo;
    }
    
    public void setAgentContactNo(String agentContactNo) {
        this.agentContactNo = agentContactNo;
    }




}


