package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1



/**
 * AgentLocation generated by hbm2java
 */
public class AgentLocation  implements java.io.Serializable {


     private Integer agentLocationId;
     private InsuranceAgent insuranceAgent;
     private Double longitude;
     private Double latitude;

    public AgentLocation() {
    }

	
    public AgentLocation(InsuranceAgent insuranceAgent) {
        this.insuranceAgent = insuranceAgent;
    }
    public AgentLocation(InsuranceAgent insuranceAgent, Double longitude, Double latitude) {
       this.insuranceAgent = insuranceAgent;
       this.longitude = longitude;
       this.latitude = latitude;
    }
   
    public Integer getAgentLocationId() {
        return this.agentLocationId;
    }
    
    public void setAgentLocationId(Integer agentLocationId) {
        this.agentLocationId = agentLocationId;
    }
    public InsuranceAgent getInsuranceAgent() {
        return this.insuranceAgent;
    }
    
    public void setInsuranceAgent(InsuranceAgent insuranceAgent) {
        this.insuranceAgent = insuranceAgent;
    }
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }




}


