package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer cityId;
     private String city;
     private Set vehicalOwners = new HashSet(0);
     private Set insuranceCompanies = new HashSet(0);
     private Set claimLocations = new HashSet(0);

    public City() {
    }

    public City(String city, Set vehicalOwners, Set insuranceCompanies, Set claimLocations) {
       this.city = city;
       this.vehicalOwners = vehicalOwners;
       this.insuranceCompanies = insuranceCompanies;
       this.claimLocations = claimLocations;
    }
   
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Set getVehicalOwners() {
        return this.vehicalOwners;
    }
    
    public void setVehicalOwners(Set vehicalOwners) {
        this.vehicalOwners = vehicalOwners;
    }
    public Set getInsuranceCompanies() {
        return this.insuranceCompanies;
    }
    
    public void setInsuranceCompanies(Set insuranceCompanies) {
        this.insuranceCompanies = insuranceCompanies;
    }
    public Set getClaimLocations() {
        return this.claimLocations;
    }
    
    public void setClaimLocations(Set claimLocations) {
        this.claimLocations = claimLocations;
    }




}


