package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClaimLocation generated by hbm2java
 */
public class ClaimLocation  implements java.io.Serializable {


     private Integer claimLocationId;
     private City city;
     private Double logitude;
     private Double latitude;
     private Set insuranceClaims = new HashSet(0);

    public ClaimLocation() {
    }

	
    public ClaimLocation(City city) {
        this.city = city;
    }
    public ClaimLocation(City city, Double logitude, Double latitude, Set insuranceClaims) {
       this.city = city;
       this.logitude = logitude;
       this.latitude = latitude;
       this.insuranceClaims = insuranceClaims;
    }
   
    public Integer getClaimLocationId() {
        return this.claimLocationId;
    }
    
    public void setClaimLocationId(Integer claimLocationId) {
        this.claimLocationId = claimLocationId;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public Double getLogitude() {
        return this.logitude;
    }
    
    public void setLogitude(Double logitude) {
        this.logitude = logitude;
    }
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    public Set getInsuranceClaims() {
        return this.insuranceClaims;
    }
    
    public void setInsuranceClaims(Set insuranceClaims) {
        this.insuranceClaims = insuranceClaims;
    }




}


