package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CompanyStatus generated by hbm2java
 */
public class CompanyStatus  implements java.io.Serializable {


     private Integer companyStatusId;
     private String companyStatus;
     private Set insuranceCompanies = new HashSet(0);

    public CompanyStatus() {
    }

    public CompanyStatus(String companyStatus, Set insuranceCompanies) {
       this.companyStatus = companyStatus;
       this.insuranceCompanies = insuranceCompanies;
    }
   
    public Integer getCompanyStatusId() {
        return this.companyStatusId;
    }
    
    public void setCompanyStatusId(Integer companyStatusId) {
        this.companyStatusId = companyStatusId;
    }
    public String getCompanyStatus() {
        return this.companyStatus;
    }
    
    public void setCompanyStatus(String companyStatus) {
        this.companyStatus = companyStatus;
    }
    public Set getInsuranceCompanies() {
        return this.insuranceCompanies;
    }
    
    public void setInsuranceCompanies(Set insuranceCompanies) {
        this.insuranceCompanies = insuranceCompanies;
    }




}


