package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CompanyLogo generated by hbm2java
 */
public class CompanyLogo  implements java.io.Serializable {


     private Integer companyLogoId;
     private String logoUrl;
     private Set insuranceCompanies = new HashSet(0);

    public CompanyLogo() {
    }

    public CompanyLogo(String logoUrl, Set insuranceCompanies) {
       this.logoUrl = logoUrl;
       this.insuranceCompanies = insuranceCompanies;
    }
   
    public Integer getCompanyLogoId() {
        return this.companyLogoId;
    }
    
    public void setCompanyLogoId(Integer companyLogoId) {
        this.companyLogoId = companyLogoId;
    }
    public String getLogoUrl() {
        return this.logoUrl;
    }
    
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }
    public Set getInsuranceCompanies() {
        return this.insuranceCompanies;
    }
    
    public void setInsuranceCompanies(Set insuranceCompanies) {
        this.insuranceCompanies = insuranceCompanies;
    }




}


