package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DamageType generated by hbm2java
 */
public class DamageType  implements java.io.Serializable {


     private Integer damageTypeId;
     private String damageType;
     private Set insuranceClaims = new HashSet(0);

    public DamageType() {
    }

    public DamageType(String damageType, Set insuranceClaims) {
       this.damageType = damageType;
       this.insuranceClaims = insuranceClaims;
    }
   
    public Integer getDamageTypeId() {
        return this.damageTypeId;
    }
    
    public void setDamageTypeId(Integer damageTypeId) {
        this.damageTypeId = damageTypeId;
    }
    public String getDamageType() {
        return this.damageType;
    }
    
    public void setDamageType(String damageType) {
        this.damageType = damageType;
    }
    public Set getInsuranceClaims() {
        return this.insuranceClaims;
    }
    
    public void setInsuranceClaims(Set insuranceClaims) {
        this.insuranceClaims = insuranceClaims;
    }




}


