package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1



/**
 * EvidencePhoto generated by hbm2java
 */
public class EvidencePhoto  implements java.io.Serializable {


     private Integer evidenceImageId;
     private EvidencePhotoType evidencePhotoType;
     private InsuranceClaim insuranceClaim;
     private String evidenceImageUrl;

    public EvidencePhoto() {
    }

	
    public EvidencePhoto(EvidencePhotoType evidencePhotoType, InsuranceClaim insuranceClaim) {
        this.evidencePhotoType = evidencePhotoType;
        this.insuranceClaim = insuranceClaim;
    }
    public EvidencePhoto(EvidencePhotoType evidencePhotoType, InsuranceClaim insuranceClaim, String evidenceImageUrl) {
       this.evidencePhotoType = evidencePhotoType;
       this.insuranceClaim = insuranceClaim;
       this.evidenceImageUrl = evidenceImageUrl;
    }
   
    public Integer getEvidenceImageId() {
        return this.evidenceImageId;
    }
    
    public void setEvidenceImageId(Integer evidenceImageId) {
        this.evidenceImageId = evidenceImageId;
    }
    public EvidencePhotoType getEvidencePhotoType() {
        return this.evidencePhotoType;
    }
    
    public void setEvidencePhotoType(EvidencePhotoType evidencePhotoType) {
        this.evidencePhotoType = evidencePhotoType;
    }
    public InsuranceClaim getInsuranceClaim() {
        return this.insuranceClaim;
    }
    
    public void setInsuranceClaim(InsuranceClaim insuranceClaim) {
        this.insuranceClaim = insuranceClaim;
    }
    public String getEvidenceImageUrl() {
        return this.evidenceImageUrl;
    }
    
    public void setEvidenceImageUrl(String evidenceImageUrl) {
        this.evidenceImageUrl = evidenceImageUrl;
    }




}


