package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InsuranceClaim generated by hbm2java
 */
public class InsuranceClaim  implements java.io.Serializable {


     private Integer insuranceClaimId;
     private ClaimLocation claimLocation;
     private ClaimStatus claimStatus;
     private DamageType damageType;
     private InsuranceAgent insuranceAgent;
     private InsuredVehical insuredVehical;
     private String claimDescription;
     private Date claimDatetime;
     private Set evidencePhotos = new HashSet(0);
     private Set respondMessages = new HashSet(0);

    public InsuranceClaim() {
    }

	
    public InsuranceClaim(ClaimStatus claimStatus, DamageType damageType, InsuredVehical insuredVehical) {
        this.claimStatus = claimStatus;
        this.damageType = damageType;
        this.insuredVehical = insuredVehical;
    }
    public InsuranceClaim(ClaimLocation claimLocation, ClaimStatus claimStatus, DamageType damageType, InsuranceAgent insuranceAgent, InsuredVehical insuredVehical, String claimDescription, Date claimDatetime, Set evidencePhotos, Set respondMessages) {
       this.claimLocation = claimLocation;
       this.claimStatus = claimStatus;
       this.damageType = damageType;
       this.insuranceAgent = insuranceAgent;
       this.insuredVehical = insuredVehical;
       this.claimDescription = claimDescription;
       this.claimDatetime = claimDatetime;
       this.evidencePhotos = evidencePhotos;
       this.respondMessages = respondMessages;
    }
   
    public Integer getInsuranceClaimId() {
        return this.insuranceClaimId;
    }
    
    public void setInsuranceClaimId(Integer insuranceClaimId) {
        this.insuranceClaimId = insuranceClaimId;
    }
    public ClaimLocation getClaimLocation() {
        return this.claimLocation;
    }
    
    public void setClaimLocation(ClaimLocation claimLocation) {
        this.claimLocation = claimLocation;
    }
    public ClaimStatus getClaimStatus() {
        return this.claimStatus;
    }
    
    public void setClaimStatus(ClaimStatus claimStatus) {
        this.claimStatus = claimStatus;
    }
    public DamageType getDamageType() {
        return this.damageType;
    }
    
    public void setDamageType(DamageType damageType) {
        this.damageType = damageType;
    }
    public InsuranceAgent getInsuranceAgent() {
        return this.insuranceAgent;
    }
    
    public void setInsuranceAgent(InsuranceAgent insuranceAgent) {
        this.insuranceAgent = insuranceAgent;
    }
    public InsuredVehical getInsuredVehical() {
        return this.insuredVehical;
    }
    
    public void setInsuredVehical(InsuredVehical insuredVehical) {
        this.insuredVehical = insuredVehical;
    }
    public String getClaimDescription() {
        return this.claimDescription;
    }
    
    public void setClaimDescription(String claimDescription) {
        this.claimDescription = claimDescription;
    }
    public Date getClaimDatetime() {
        return this.claimDatetime;
    }
    
    public void setClaimDatetime(Date claimDatetime) {
        this.claimDatetime = claimDatetime;
    }
    public Set getEvidencePhotos() {
        return this.evidencePhotos;
    }
    
    public void setEvidencePhotos(Set evidencePhotos) {
        this.evidencePhotos = evidencePhotos;
    }
    public Set getRespondMessages() {
        return this.respondMessages;
    }
    
    public void setRespondMessages(Set respondMessages) {
        this.respondMessages = respondMessages;
    }




}


