package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InsuredPeriodType generated by hbm2java
 */
public class InsuredPeriodType  implements java.io.Serializable {


     private Integer insuredPeriodTypeId;
     private String insuredPeriodType;
     private Set insuredPeriods = new HashSet(0);

    public InsuredPeriodType() {
    }

    public InsuredPeriodType(String insuredPeriodType, Set insuredPeriods) {
       this.insuredPeriodType = insuredPeriodType;
       this.insuredPeriods = insuredPeriods;
    }
   
    public Integer getInsuredPeriodTypeId() {
        return this.insuredPeriodTypeId;
    }
    
    public void setInsuredPeriodTypeId(Integer insuredPeriodTypeId) {
        this.insuredPeriodTypeId = insuredPeriodTypeId;
    }
    public String getInsuredPeriodType() {
        return this.insuredPeriodType;
    }
    
    public void setInsuredPeriodType(String insuredPeriodType) {
        this.insuredPeriodType = insuredPeriodType;
    }
    public Set getInsuredPeriods() {
        return this.insuredPeriods;
    }
    
    public void setInsuredPeriods(Set insuredPeriods) {
        this.insuredPeriods = insuredPeriods;
    }




}


