package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InsuredPeriod generated by hbm2java
 */
public class InsuredPeriod  implements java.io.Serializable {


     private Integer insuredPeriodId;
     private InsuredPeriodType insuredPeriodType;
     private Double insuredPeriod;
     private Set insuranceCoverages = new HashSet(0);

    public InsuredPeriod() {
    }

	
    public InsuredPeriod(InsuredPeriodType insuredPeriodType) {
        this.insuredPeriodType = insuredPeriodType;
    }
    public InsuredPeriod(InsuredPeriodType insuredPeriodType, Double insuredPeriod, Set insuranceCoverages) {
       this.insuredPeriodType = insuredPeriodType;
       this.insuredPeriod = insuredPeriod;
       this.insuranceCoverages = insuranceCoverages;
    }
   
    public Integer getInsuredPeriodId() {
        return this.insuredPeriodId;
    }
    
    public void setInsuredPeriodId(Integer insuredPeriodId) {
        this.insuredPeriodId = insuredPeriodId;
    }
    public InsuredPeriodType getInsuredPeriodType() {
        return this.insuredPeriodType;
    }
    
    public void setInsuredPeriodType(InsuredPeriodType insuredPeriodType) {
        this.insuredPeriodType = insuredPeriodType;
    }
    public Double getInsuredPeriod() {
        return this.insuredPeriod;
    }
    
    public void setInsuredPeriod(Double insuredPeriod) {
        this.insuredPeriod = insuredPeriod;
    }
    public Set getInsuranceCoverages() {
        return this.insuranceCoverages;
    }
    
    public void setInsuranceCoverages(Set insuranceCoverages) {
        this.insuranceCoverages = insuranceCoverages;
    }




}


