package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InsuranceAgent generated by hbm2java
 */
public class InsuranceAgent  implements java.io.Serializable {


     private String agentNic;
     private AgentStatus agentStatus;
     private InsuranceCompany insuranceCompany;
     private String firstName;
     private String lastName;
     private String email;
     private String username;
     private String password;
     private Date dob;
     private String profileImgUrl;
     private Set insuranceClaims = new HashSet(0);
     private Set agentLocations = new HashSet(0);
     private Set agentContactNos = new HashSet(0);

    public InsuranceAgent() {
    }

	
    public InsuranceAgent(String agentNic, AgentStatus agentStatus, InsuranceCompany insuranceCompany) {
        this.agentNic = agentNic;
        this.agentStatus = agentStatus;
        this.insuranceCompany = insuranceCompany;
    }
    public InsuranceAgent(String agentNic, AgentStatus agentStatus, InsuranceCompany insuranceCompany, String firstName, String lastName, String email, String username, String password, Date dob, String profileImgUrl, Set insuranceClaims, Set agentLocations, Set agentContactNos) {
       this.agentNic = agentNic;
       this.agentStatus = agentStatus;
       this.insuranceCompany = insuranceCompany;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.username = username;
       this.password = password;
       this.dob = dob;
       this.profileImgUrl = profileImgUrl;
       this.insuranceClaims = insuranceClaims;
       this.agentLocations = agentLocations;
       this.agentContactNos = agentContactNos;
    }
   
    public String getAgentNic() {
        return this.agentNic;
    }
    
    public void setAgentNic(String agentNic) {
        this.agentNic = agentNic;
    }
    public AgentStatus getAgentStatus() {
        return this.agentStatus;
    }
    
    public void setAgentStatus(AgentStatus agentStatus) {
        this.agentStatus = agentStatus;
    }
    public InsuranceCompany getInsuranceCompany() {
        return this.insuranceCompany;
    }
    
    public void setInsuranceCompany(InsuranceCompany insuranceCompany) {
        this.insuranceCompany = insuranceCompany;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getProfileImgUrl() {
        return this.profileImgUrl;
    }
    
    public void setProfileImgUrl(String profileImgUrl) {
        this.profileImgUrl = profileImgUrl;
    }
    public Set getInsuranceClaims() {
        return this.insuranceClaims;
    }
    
    public void setInsuranceClaims(Set insuranceClaims) {
        this.insuranceClaims = insuranceClaims;
    }
    public Set getAgentLocations() {
        return this.agentLocations;
    }
    
    public void setAgentLocations(Set agentLocations) {
        this.agentLocations = agentLocations;
    }
    public Set getAgentContactNos() {
        return this.agentContactNos;
    }
    
    public void setAgentContactNos(Set agentContactNos) {
        this.agentContactNos = agentContactNos;
    }




}


