package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InsuranceType generated by hbm2java
 */
public class InsuranceType  implements java.io.Serializable {


     private Integer insuranceTypeId;
     private String insuranceType;
     private Set insuranceCoverages = new HashSet(0);

    public InsuranceType() {
    }

    public InsuranceType(String insuranceType, Set insuranceCoverages) {
       this.insuranceType = insuranceType;
       this.insuranceCoverages = insuranceCoverages;
    }
   
    public Integer getInsuranceTypeId() {
        return this.insuranceTypeId;
    }
    
    public void setInsuranceTypeId(Integer insuranceTypeId) {
        this.insuranceTypeId = insuranceTypeId;
    }
    public String getInsuranceType() {
        return this.insuranceType;
    }
    
    public void setInsuranceType(String insuranceType) {
        this.insuranceType = insuranceType;
    }
    public Set getInsuranceCoverages() {
        return this.insuranceCoverages;
    }
    
    public void setInsuranceCoverages(Set insuranceCoverages) {
        this.insuranceCoverages = insuranceCoverages;
    }




}


