package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InsuredVehical generated by hbm2java
 */
public class InsuredVehical  implements java.io.Serializable {


     private String insuredVehicalId;
     private InsuranceCompany insuranceCompany;
     private InsuranceCoverage insuranceCoverage;
     private VehicalColor vehicalColor;
     private VehicalModel vehicalModel;
     private VehicalOwner vehicalOwner;
     private VehicalStatus vehicalStatus;
     private VehicalType vehicalType;
     private Integer yearOfMade;
     private String enginNo;
     private String chasisNo;
     private Set insuranceClaims = new HashSet(0);
     private Set vehicalImages = new HashSet(0);

    public InsuredVehical() {
    }

	
    public InsuredVehical(String insuredVehicalId, InsuranceCompany insuranceCompany, InsuranceCoverage insuranceCoverage, VehicalColor vehicalColor, VehicalModel vehicalModel, VehicalOwner vehicalOwner, VehicalStatus vehicalStatus, VehicalType vehicalType) {
        this.insuredVehicalId = insuredVehicalId;
        this.insuranceCompany = insuranceCompany;
        this.insuranceCoverage = insuranceCoverage;
        this.vehicalColor = vehicalColor;
        this.vehicalModel = vehicalModel;
        this.vehicalOwner = vehicalOwner;
        this.vehicalStatus = vehicalStatus;
        this.vehicalType = vehicalType;
    }
    public InsuredVehical(String insuredVehicalId, InsuranceCompany insuranceCompany, InsuranceCoverage insuranceCoverage, VehicalColor vehicalColor, VehicalModel vehicalModel, VehicalOwner vehicalOwner, VehicalStatus vehicalStatus, VehicalType vehicalType, Integer yearOfMade, String enginNo, String chasisNo, Set insuranceClaims, Set vehicalImages) {
       this.insuredVehicalId = insuredVehicalId;
       this.insuranceCompany = insuranceCompany;
       this.insuranceCoverage = insuranceCoverage;
       this.vehicalColor = vehicalColor;
       this.vehicalModel = vehicalModel;
       this.vehicalOwner = vehicalOwner;
       this.vehicalStatus = vehicalStatus;
       this.vehicalType = vehicalType;
       this.yearOfMade = yearOfMade;
       this.enginNo = enginNo;
       this.chasisNo = chasisNo;
       this.insuranceClaims = insuranceClaims;
       this.vehicalImages = vehicalImages;
    }
   
    public String getInsuredVehicalId() {
        return this.insuredVehicalId;
    }
    
    public void setInsuredVehicalId(String insuredVehicalId) {
        this.insuredVehicalId = insuredVehicalId;
    }
    public InsuranceCompany getInsuranceCompany() {
        return this.insuranceCompany;
    }
    
    public void setInsuranceCompany(InsuranceCompany insuranceCompany) {
        this.insuranceCompany = insuranceCompany;
    }
    public InsuranceCoverage getInsuranceCoverage() {
        return this.insuranceCoverage;
    }
    
    public void setInsuranceCoverage(InsuranceCoverage insuranceCoverage) {
        this.insuranceCoverage = insuranceCoverage;
    }
    public VehicalColor getVehicalColor() {
        return this.vehicalColor;
    }
    
    public void setVehicalColor(VehicalColor vehicalColor) {
        this.vehicalColor = vehicalColor;
    }
    public VehicalModel getVehicalModel() {
        return this.vehicalModel;
    }
    
    public void setVehicalModel(VehicalModel vehicalModel) {
        this.vehicalModel = vehicalModel;
    }
    public VehicalOwner getVehicalOwner() {
        return this.vehicalOwner;
    }
    
    public void setVehicalOwner(VehicalOwner vehicalOwner) {
        this.vehicalOwner = vehicalOwner;
    }
    public VehicalStatus getVehicalStatus() {
        return this.vehicalStatus;
    }
    
    public void setVehicalStatus(VehicalStatus vehicalStatus) {
        this.vehicalStatus = vehicalStatus;
    }
    public VehicalType getVehicalType() {
        return this.vehicalType;
    }
    
    public void setVehicalType(VehicalType vehicalType) {
        this.vehicalType = vehicalType;
    }
    public Integer getYearOfMade() {
        return this.yearOfMade;
    }
    
    public void setYearOfMade(Integer yearOfMade) {
        this.yearOfMade = yearOfMade;
    }
    public String getEnginNo() {
        return this.enginNo;
    }
    
    public void setEnginNo(String enginNo) {
        this.enginNo = enginNo;
    }
    public String getChasisNo() {
        return this.chasisNo;
    }
    
    public void setChasisNo(String chasisNo) {
        this.chasisNo = chasisNo;
    }
    public Set getInsuranceClaims() {
        return this.insuranceClaims;
    }
    
    public void setInsuranceClaims(Set insuranceClaims) {
        this.insuranceClaims = insuranceClaims;
    }
    public Set getVehicalImages() {
        return this.vehicalImages;
    }
    
    public void setVehicalImages(Set vehicalImages) {
        this.vehicalImages = vehicalImages;
    }




}


