package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1



/**
 * VehicalImage generated by hbm2java
 */
public class VehicalImage  implements java.io.Serializable {


     private Integer vehicalImageId;
     private InsuredVehical insuredVehical;
     private String vehicalImageUrl;

    public VehicalImage() {
    }

	
    public VehicalImage(InsuredVehical insuredVehical) {
        this.insuredVehical = insuredVehical;
    }
    public VehicalImage(InsuredVehical insuredVehical, String vehicalImageUrl) {
       this.insuredVehical = insuredVehical;
       this.vehicalImageUrl = vehicalImageUrl;
    }
   
    public Integer getVehicalImageId() {
        return this.vehicalImageId;
    }
    
    public void setVehicalImageId(Integer vehicalImageId) {
        this.vehicalImageId = vehicalImageId;
    }
    public InsuredVehical getInsuredVehical() {
        return this.insuredVehical;
    }
    
    public void setInsuredVehical(InsuredVehical insuredVehical) {
        this.insuredVehical = insuredVehical;
    }
    public String getVehicalImageUrl() {
        return this.vehicalImageUrl;
    }
    
    public void setVehicalImageUrl(String vehicalImageUrl) {
        this.vehicalImageUrl = vehicalImageUrl;
    }




}


