package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VehicalType generated by hbm2java
 */
public class VehicalType  implements java.io.Serializable {


     private Integer vehicalTypeId;
     private String vehicalType;
     private Set insuredVehicals = new HashSet(0);

    public VehicalType() {
    }

    public VehicalType(String vehicalType, Set insuredVehicals) {
       this.vehicalType = vehicalType;
       this.insuredVehicals = insuredVehicals;
    }
   
    public Integer getVehicalTypeId() {
        return this.vehicalTypeId;
    }
    
    public void setVehicalTypeId(Integer vehicalTypeId) {
        this.vehicalTypeId = vehicalTypeId;
    }
    public String getVehicalType() {
        return this.vehicalType;
    }
    
    public void setVehicalType(String vehicalType) {
        this.vehicalType = vehicalType;
    }
    public Set getInsuredVehicals() {
        return this.insuredVehicals;
    }
    
    public void setInsuredVehicals(Set insuredVehicals) {
        this.insuredVehicals = insuredVehicals;
    }




}


