package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VehicalModel generated by hbm2java
 */
public class VehicalModel  implements java.io.Serializable {


     private Integer vehicalModelId;
     private VehicalBrand vehicalBrand;
     private String vehicalModel;
     private Set insuredVehicals = new HashSet(0);

    public VehicalModel() {
    }

	
    public VehicalModel(VehicalBrand vehicalBrand) {
        this.vehicalBrand = vehicalBrand;
    }
    public VehicalModel(VehicalBrand vehicalBrand, String vehicalModel, Set insuredVehicals) {
       this.vehicalBrand = vehicalBrand;
       this.vehicalModel = vehicalModel;
       this.insuredVehicals = insuredVehicals;
    }
   
    public Integer getVehicalModelId() {
        return this.vehicalModelId;
    }
    
    public void setVehicalModelId(Integer vehicalModelId) {
        this.vehicalModelId = vehicalModelId;
    }
    public VehicalBrand getVehicalBrand() {
        return this.vehicalBrand;
    }
    
    public void setVehicalBrand(VehicalBrand vehicalBrand) {
        this.vehicalBrand = vehicalBrand;
    }
    public String getVehicalModel() {
        return this.vehicalModel;
    }
    
    public void setVehicalModel(String vehicalModel) {
        this.vehicalModel = vehicalModel;
    }
    public Set getInsuredVehicals() {
        return this.insuredVehicals;
    }
    
    public void setInsuredVehicals(Set insuredVehicals) {
        this.insuredVehicals = insuredVehicals;
    }




}


