package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VehicalStatus generated by hbm2java
 */
public class VehicalStatus  implements java.io.Serializable {


     private Integer vehicalStatusId;
     private String vehicalStatus;
     private Set insuredVehicals = new HashSet(0);

    public VehicalStatus() {
    }

    public VehicalStatus(String vehicalStatus, Set insuredVehicals) {
       this.vehicalStatus = vehicalStatus;
       this.insuredVehicals = insuredVehicals;
    }
   
    public Integer getVehicalStatusId() {
        return this.vehicalStatusId;
    }
    
    public void setVehicalStatusId(Integer vehicalStatusId) {
        this.vehicalStatusId = vehicalStatusId;
    }
    public String getVehicalStatus() {
        return this.vehicalStatus;
    }
    
    public void setVehicalStatus(String vehicalStatus) {
        this.vehicalStatus = vehicalStatus;
    }
    public Set getInsuredVehicals() {
        return this.insuredVehicals;
    }
    
    public void setInsuredVehicals(Set insuredVehicals) {
        this.insuredVehicals = insuredVehicals;
    }




}


