package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VehicalColor generated by hbm2java
 */
public class VehicalColor  implements java.io.Serializable {


     private Integer vehicalColorId;
     private String vehicalColor;
     private Set insuredVehicals = new HashSet(0);

    public VehicalColor() {
    }

    public VehicalColor(String vehicalColor, Set insuredVehicals) {
       this.vehicalColor = vehicalColor;
       this.insuredVehicals = insuredVehicals;
    }
   
    public Integer getVehicalColorId() {
        return this.vehicalColorId;
    }
    
    public void setVehicalColorId(Integer vehicalColorId) {
        this.vehicalColorId = vehicalColorId;
    }
    public String getVehicalColor() {
        return this.vehicalColor;
    }
    
    public void setVehicalColor(String vehicalColor) {
        this.vehicalColor = vehicalColor;
    }
    public Set getInsuredVehicals() {
        return this.insuredVehicals;
    }
    
    public void setInsuredVehicals(Set insuredVehicals) {
        this.insuredVehicals = insuredVehicals;
    }




}


