package Db;
// Generated Mar 15, 2017 2:10:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VehicalBrand generated by hbm2java
 */
public class VehicalBrand  implements java.io.Serializable {


     private Integer vehicalBrandId;
     private String vehicalBrand;
     private Set vehicalModels = new HashSet(0);

    public VehicalBrand() {
    }

    public VehicalBrand(String vehicalBrand, Set vehicalModels) {
       this.vehicalBrand = vehicalBrand;
       this.vehicalModels = vehicalModels;
    }
   
    public Integer getVehicalBrandId() {
        return this.vehicalBrandId;
    }
    
    public void setVehicalBrandId(Integer vehicalBrandId) {
        this.vehicalBrandId = vehicalBrandId;
    }
    public String getVehicalBrand() {
        return this.vehicalBrand;
    }
    
    public void setVehicalBrand(String vehicalBrand) {
        this.vehicalBrand = vehicalBrand;
    }
    public Set getVehicalModels() {
        return this.vehicalModels;
    }
    
    public void setVehicalModels(Set vehicalModels) {
        this.vehicalModels = vehicalModels;
    }




}


